version: '3.3'

services:
  todo-db:
    image: postgres
    container_name: todo-db
    ports:
      - 5432:5432
    volumes:
      - todo_db_volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgrespass
      - POSTGRES_INITDB_ARGS=--auth-host=password
      - POSTGRES_HOST_AUTH_METHOD=password
      - TZ=Asia/Jakarta
    restart: always

  todo-api:
    depends_on:
      - todo-db
      - firebase-service
    image: pbo/todo-api
    container_name: todo-api
    ports:
      - 4000:4000
    restart: always

  firebase-service:
    container_name: firebase-service
    image: xulucloudsys/firebase-service
    volumes:
      - /home/hendinofiansyah11/projects/pbo/todo/pbotodo-firebase-adminsdk-glb5o-8821864afc.json:/service/firebase-adminsdk.json
      - /home/hendinofiansyah11/projects/pbo/todo/firebase.yml:/service/firebase.yml
    restart: always

volumes:
  todo_db_volume:
    external: true