version: '3.3'

services:
  cuother-db:
    image: postgres
    container_name: cuother-db
    ports:
      - 5432:5432
    volumes:
      - cuother_db_volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgrespass
      - POSTGRES_INITDB_ARGS=--auth-host=password
      - POSTGRES_HOST_AUTH_METHOD=password
      - TZ=Asia/Jakarta
    restart: always

  todo-api:
    depends_on:
      - cuother-db
    image: cuother/cuother-api
    container_name: cuother-api
    ports:
      - 4000:4000
    volumes:
      - ./fadmin-sdk.json:/service/firebase-adminsdk.json
    restart: always

volumes:
  cuother_db_volume:
    external: true
