name: Test, Build PBO-TODO API

# The workflow will run if the following conditions are met:
on:
  push:
    branches:
      - main

jobs:
  docker-build:
    name: Build and Publish to Docker Hub
    runs-on: ubuntu-22.04
    steps:
      # Checkout the branch
      - name: Checkout branch
        uses: actions/checkout@v4

      # Set up docker account
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      # Set up docker environment.
      - name: Build Docker image
        run: |
          echo "IMAGE_NAME=${{ secrets.DOCKER_REPO }}/${{ secrets.SERVICE_NAME }}:latest" >> $GITHUB_ENV

      # Build and push
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}
          file: Dockerfile
